# Generated by Django 5.1 on 2025-10-31 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Referral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(db_index=True, max_length=255, unique=True)),
                ('status', models.CharField(choices=[('INVITATION_SENT', 'Invitation Sent'), ('APPLICATION_RECEIVED', 'Application Received'), ('JOINED', 'Joined'), ('DECLINED', 'Declined')], default='INVITATION_SENT', max_length=30)),
                ('referred_date', models.DateTimeField(auto_now_add=True)),
                ('last_sent_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-referred_date'],
            },
        ),
    ]
