# Generated by Django 5.1 on 2025-11-02 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='joined_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
